FORMAT: 1A

# API Transporte Público

API para gerenciar recursos para ônibus públicos.

# Cidades

## Recuperar / Adicionar [/cidades]

### Obter todas as cidades [GET]

+ Response 400 (application/json)

        {
            "status": false,
            "message": "Erro desconhecido. Por favor tente novamente."
        }

+ Response 200 (application/json)

        {
            "status": false,
            "message": "Não existem cidades cadastradas."
        }

+ Response 200 (application/json)

        {
            "status": true,
            "cidades": [
                {
                    "id": "1",
                    "nome": "Londrina",
                    "estado": "PR"
                },
                {
                    "id": "2",
                    "nome": "Maringá",
                    "estado": "PR"
                },
                {
                    "id": "3",
                    "nome": "Curitiba",
                    "estado": "PR"
                }
            ]
        }

### Adiciona uma nova cidade [POST]

+ Request (application/json)

        {
            "nome": "Cascavel",
            "estado": "PR"
        }

+ Response 400 (application/json)

        {
            "status": false,
            "message": "Erro desconhecido. Por favor tente novamente."
        }

+ Response 200 (application/json)

        {
            "status": false,
            "message": "Os campos 'nome' e 'estado' são obrigatórios"
        }

+ Response 201 (application/json)

    + Headers

            Location: /cidades/4

    + Body

            {
                "status": true,
                "id": "4"
                "status": "Cidade cadastrada com sucesso"
            }

## Recuperar /  Editar / Deletar [/cidades/:id]

### Obter informações de uma cidade [GET]

+ Request (application/json)

        {
            "id": "1"
        }

+ Response 400 (application/json)

        {
            "status": false,
            "message": "Erro desconhecido. Por favor tente novamente."
        }

+ Response 200 (application/json)

        {
            "status": false,
            "message": "Não existe cidade com esse id."
        }

+ Response 200 (application/json)

        {
            "status": true,
            "cidade": [
                {
                    "id": 1,
                    "nome": "Londrina",
                    "estado": "PR"
                }
            ]
        }

### Editar um registro de uma cidade [PUT]

+ Request (application/json)

        {
            "id": "4",
            "nome": "Ponta Grossa"
        }
        
+ Response 200 (application/json)

        {
            "status": true,
            "id": "4"
            "status": "Cidade editada com sucesso"
        }

### Deletar um registro de uma cidade [DELETE]

+ Request (application/json)

        {
            "id": "4"
        }

+ Response 400 (application/json)

        {
            "status": false,
            "message": "Erro desconhecido. Por favor tente novamente."
        }

+ Response 200 (application/json)

        {
            "status": false,
            "message": "Não existe cidade com esse id."
        }

+ Response 200 (application/json)

        {
            "status": true,
            "message": "Cidade removida com sucesso"
        }
